version: "2"
run:
  concurrency: 6
linters:
  default: none
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ireturn
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl_v5
    - zerologlint
    # - depguard
    # - err113
    # - exhaustruct
    # - gosec
    # - lll
    # - noinlineerr
    # - nonamedreturns
    # - testpackage
    # - varnamelen
    # - wrapcheck
  settings:
    cyclop:
      max-complexity: 15
    funcorder:
      struct-method: false
    funlen:
      lines: 85
      statements: 50
    gocognit:
      min-complexity: 35
    gocritic:
      enable-all: true
    ireturn:
      allow:
        - error
        - stdlib
        - github.com/cri-o/ocicni/pkg/ocicni.CNIPlugin
        - github.com/containernetworking/cni/pkg/types.Result
    mnd:
      ignored-numbers:
        - "0o755"
      ignored-functions:
        - "strings.SplitN"
    nestif:
      min-complexity: 11
    revive:
      rules:
        - name: dot-imports
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
